### ISSUE TITLE
Example Not working!

### ISSUE THREAD

**Issue by osoblanco** [cair/deep-rts#17]
After installing DeepRts I cannot run the code as it is either missing dependencies or smth. like that.

```
AttributeError: 'DeepRTS.Engine.Config' object has no attribute 'set_start_wood'
```

**Comment by perara** [comment]
I assume you ran the code in the README.md.
This is probably outdated, how much, I don't know.  See the examples in the coding directory :)

**Comment by osoblanco** [comment]
Oh ok. Also After starting the rendering should the window turn grey after a while ?
![Screenshot from 2020-06-25 14-13-14](https://user-images.githubusercontent.com/8036160/85734758-29a2cf80-b6f5-11ea-9afb-f7de19538da2.png)

**Comment by perara** [comment]
Does it render stuff at all, or just the first picture?
If it doesn't render at all it means that you have to explicitly call the render function to draw the pixel buffer onto your screen :)

If I've deactivated that by default it is because it boosts the speed significantly

**Comment by osoblanco** [comment]
AAA ok. It does render everything for several seconds and then suddenly goes grayscale while still rendering all the actions. How exactly can I do rendering completely?

**Comment by carlosgmartin** [comment]
Can the top-level README example be updated (or perhaps moved entirely to the coding directory, with a link to the file), since the `main.py` example in the `coding` directory lacks illustration of certain features like rendering and configuration? I fixed two errors so far, changing `set_start_wood` to `set_start_lumber` and `GoldThousand` to `GoldCollectOnePlayerFifteen`. However, I still get
```
Traceback (most recent call last):
  File "example.py", line 42, in <module>
    env = scenario.GoldCollectOnePlayerFifteen(game)
  File "/usr/local/lib/python3.8/site-packages/DeepRTS/python/scenario/envs.py", line 10, in __init__
    engconf = config["engine"] if "engine" in config else {}
TypeError: argument of type 'Game' is not iterable
```
(relevant code [here](https://github.com/cair/deep-rts/blob/master/DeepRTS/python/scenario/envs.py#L8)) as well as `TypeError: step() got an unexpected keyword argument 'render'` (relevant code [here](https://github.com/cair/deep-rts/blob/master/DeepRTS/python/scenario/engine.py)).

This game environment looks very promising, so a fully working example would be very helpful for new users.

Side question: Are there plans to add fog-of-war soon, as mentioned in the [paper](https://ieeexplore.ieee.org/abstract/document/8490409)?
